
pokemons = [
    {"id": 1, "name": "Bulbasaur", "attack": 49, "live": 45, "type": ["Grass", "Poison"]},
    {"id": 2, "name": "Ivysaur", "attack": 62, "live": 60, "type": ["Grass", "Poison"]},
    {"id": 3, "name": "Venusaur", "attack": 82, "live": 80, "type": ["Grass", "Poison"]},
    {"id": 4, "name": "Charmander", "attack": 52, "live": 39, "type": ["Fire"]},
    {"id": 5, "name": "Charmeleon", "attack": 64, "live": 58, "type": ["Fire"]},
    {"id": 6, "name": "Charizard", "attack": 84, "live": 78, "type": ["Fire", "Flying"]},
    {"id": 7, "name": "Squirtle", "attack": 48, "live": 44, "type": ["Water"]},
    {"id": 8, "name": "Wartortle", "attack": 63, "live": 59, "type": ["Water"]},
    {"id": 9, "name": "Blastoise", "attack": 83, "live": 79, "type": ["Water"]},
    {"id": 10, "name": "Caterpie", "attack": 30, "live": 45, "type": ["Bug"]},
    {"id": 11, "name": "Metapod", "attack": 20, "live": 50, "type": ["Bug"]},
    {"id": 12, "name": "Butterfree", "attack": 45, "live": 60, "type": ["Bug", "Flying"]},
    {"id": 13, "name": "Weedle", "attack": 35, "live": 40, "type": ["Bug", "Poison"]},
    {"id": 14, "name": "Kakuna", "attack": 25, "live": 45, "type": ["Bug", "Poison"]},
    {"id": 15, "name": "Beedrill", "attack": 90, "live": 65, "type": ["Bug", "Poison"]},
    {"id": 16, "name": "Pidgey", "attack": 45, "live": 40, "type": ["Normal", "Flying"]},
    {"id": 17, "name": "Pidgeotto", "attack": 60, "live": 63, "type": ["Normal", "Flying"]},
    {"id": 18, "name": "Pidgeot", "attack": 80, "live": 83, "type": ["Normal", "Flying"]},
    {"id": 19, "name": "Rattata", "attack": 56, "live": 30, "type": ["Normal"]},
    {"id": 20, "name": "Raticate", "attack": 81, "live": 55, "type": ["Normal"]},
    {"id": 21, "name": "Spearow", "attack": 60, "live": 40, "type": ["Normal", "Flying"]},
    {"id": 22, "name": "Fearow", "attack": 90, "live": 65, "type": ["Normal", "Flying"]},
    {"id": 23, "name": "Ekans", "attack": 60, "live": 35, "type": ["Poison"]},
    {"id": 24, "name": "Arbok", "attack": 85, "live": 60, "type": ["Poison"]},
    {"id": 25, "name": "Pikachu", "attack": 55, "live": 35, "type": ["Electric"]},
    {"id": 26, "name": "Raichu", "attack": 90, "live": 60, "type": ["Electric"]},
    {"id": 27, "name": "Sandshrew", "attack": 75, "live": 50, "type": ["Ground"]},
    {"id": 28, "name": "Sandslash", "attack": 100, "live": 75, "type": ["Ground"]},
    {"id": 29, "name": "NidoranF", "attack": 47, "live": 55, "type": ["Poison"]},
    {"id": 30, "name": "Nidorina", "attack": 62, "live": 70, "type": ["Poison"]},
    {"id": 31, "name": "Nidoqueen", "attack": 92, "live": 90, "type": ["Poison", "Ground"]},
    {"id": 32, "name": "NidoranM", "attack": 57, "live": 46, "type": ["Poison"]},
    {"id": 33, "name": "Nidorino", "attack": 72, "live": 61, "type": ["Poison"]},
    {"id": 34, "name": "Nidoking", "attack": 102, "live": 81, "type": ["Poison", "Ground"]},
    {"id": 35, "name": "Clefairy", "attack": 45, "live": 70, "type": ["Fairy"]},
    {"id": 36, "name": "Clefable", "attack": 70, "live": 95, "type": ["Fairy"]},
    {"id": 37, "name": "Vulpix", "attack": 41, "live": 38, "type": ["Fire"]},
    {"id": 38, "name": "Ninetales", "attack": 76, "live": 73, "type": ["Fire"]},
    {"id": 39, "name": "Jigglypuff", "attack": 45, "live": 115, "type": ["Normal", "Fairy"]},
    {"id": 40, "name": "Wigglytuff", "attack": 70, "live": 140, "type": ["Normal", "Fairy"]},
    {"id": 41, "name": "Zubat", "attack": 45, "live": 40, "type": ["Poison", "Flying"]},
    {"id": 42, "name": "Golbat", "attack": 80, "live": 75, "type": ["Poison", "Flying"]},
    {"id": 43, "name": "Oddish", "attack": 50, "live": 45, "type": ["Grass", "Poison"]},
    {"id": 44, "name": "Gloom", "attack": 65, "live": 60, "type": ["Grass", "Poison"]},
    {"id": 45, "name": "Vileplume", "attack": 80, "live": 75, "type": ["Grass", "Poison"]},
    {"id": 46, "name": "Paras", "attack": 70, "live": 35, "type": ["Bug", "Grass"]},
    {"id": 47, "name": "Parasect", "attack": 95, "live": 60, "type": ["Bug", "Grass"]},
    {"id": 48, "name": "Venonat", "attack": 55, "live": 60, "type": ["Bug", "Poison"]},
    {"id": 49, "name": "Venomoth", "attack": 65, "live": 70, "type": ["Bug", "Poison"]},
    {"id": 50, "name": "Diglett", "attack": 55, "live": 10, "type": ["Ground"]},
    {"id": 51, "name": "Dugtrio", "attack": 100, "live": 35, "type": ["Ground"]},
    {"id": 52, "name": "Meowth", "attack": 45, "live": 40, "type": ["Normal"]},
    {"id": 53, "name": "Persian", "attack": 70, "live": 65, "type": ["Normal"]},
    {"id": 54, "name": "Psyduck", "attack": 52, "live": 50, "type": ["Water"]},
    {"id": 55, "name": "Golduck", "attack": 82, "live": 80, "type": ["Water"]},
    {"id": 56, "name": "Mankey", "attack": 80, "live": 40, "type": ["Fighting"]},
    {"id": 57, "name": "Primeape", "attack": 105, "live": 65, "type": ["Fighting"]},
    {"id": 58, "name": "Growlithe", "attack": 70, "live": 55, "type": ["Fire"]},
    {"id": 59, "name": "Arcanine", "attack": 110, "live": 90, "type": ["Fire"]},
    {"id": 60, "name": "Poliwag", "attack": 50, "live": 40, "type": ["Water"]},
    {"id": 61, "name": "Poliwhirl", "attack": 65, "live": 65, "type": ["Water"]},
    {"id": 62, "name": "Poliwrath", "attack": 95, "live": 90, "type": ["Water", "Fighting"]},
    {"id": 63, "name": "Abra", "attack": 20, "live": 25, "type": ["Psychic"]},
    {"id": 64, "name": "Kadabra", "attack": 35, "live": 40, "type": ["Psychic"]},
    {"id": 65, "name": "Alakazam", "attack": 50, "live": 55, "type": ["Psychic"]},
    {"id": 66, "name": "Machop", "attack": 80, "live": 70, "type": ["Fighting"]},
    {"id": 67, "name": "Machoke", "attack": 100, "live": 80, "type": ["Fighting"]},
    {"id": 68, "name": "Machamp", "attack": 130, "live": 90, "type": ["Fighting"]},
    {"id": 69, "name": "Bellsprout", "attack": 75, "live": 50, "type": ["Grass", "Poison"]},
    {"id": 70, "name": "Weepinbell", "attack": 90, "live": 65, "type": ["Grass", "Poison"]},
    {"id": 71, "name": "Victreebel", "attack": 105, "live": 80, "type": ["Grass", "Poison"]},
    {"id": 72, "name": "Tentacool", "attack": 40, "live": 40, "type": ["Water", "Poison"]},
    {"id": 73, "name": "Tentacruel", "attack": 70, "live": 80, "type": ["Water", "Poison"]},
    {"id": 74, "name": "Geodude", "attack": 80, "live": 40, "type": ["Rock", "Ground"]},
    {"id": 75, "name": "Graveler", "attack": 95, "live": 55, "type": ["Rock", "Ground"]},
    {"id": 76, "name": "Golem", "attack": 120, "live": 80, "type": ["Rock", "Ground"]},
    {"id": 77, "name": "Ponyta", "attack": 85, "live": 50, "type": ["Fire"]},
    {"id": 78, "name": "Rapidash", "attack": 100, "live": 65, "type": ["Fire"]},
    {"id": 79, "name": "Slowpoke", "attack": 65, "live": 90, "type": ["Water", "Psychic"]},
    {"id": 80, "name": "Slowbro", "attack": 75, "live": 95, "type": ["Water", "Psychic"]},
    {"id": 81, "name": "Magnemite", "attack": 35, "live": 25, "type": ["Electric", "Steel"]},
    {"id": 82, "name": "Magneton", "attack": 60, "live": 50, "type": ["Electric", "Steel"]},
    {"id": 83, "name": "Farfetchd", "attack": 90, "live": 52, "type": ["Normal", "Flying"]},
    {"id": 84, "name": "Doduo", "attack": 85, "live": 35, "type": ["Normal", "Flying"]},
    {"id": 85, "name": "Dodrio", "attack": 110, "live": 60, "type": ["Normal", "Flying"]},
    {"id": 86, "name": "Seel", "attack": 45, "live": 65, "type": ["Water"]},
    {"id": 87, "name": "Dewgong", "attack": 70, "live": 90, "type": ["Water", "Ice"]},
    {"id": 88, "name": "Grimer", "attack": 80, "live": 80, "type": ["Poison"]},
    {"id": 89, "name": "Muk", "attack": 105, "live": 105, "type": ["Poison"]},
    {"id": 90, "name": "Shellder", "attack": 65, "live": 30, "type": ["Water"]},
    {"id": 91, "name": "Cloyster", "attack": 95, "live": 50, "type": ["Water", "Ice"]},
    {"id": 92, "name": "Gastly", "attack": 35, "live": 30, "type": ["Ghost", "Poison"]},
    {"id": 93, "name": "Haunter", "attack": 50, "live": 45, "type": ["Ghost", "Poison"]},
    {"id": 94, "name": "Gengar", "attack": 65, "live": 60, "type": ["Ghost", "Poison"]},
    {"id": 95, "name": "Onix", "attack": 45, "live": 35, "type": ["Rock", "Ground"]},
    {"id": 96, "name": "Drowzee", "attack": 48, "live": 60, "type": ["Psychic"]},
    {"id": 97, "name": "Hypno", "attack": 73, "live": 85, "type": ["Psychic"]},
    {"id": 98, "name": "Krabby", "attack": 105, "live": 30, "type": ["Water"]},
    {"id": 99, "name": "Kingler", "attack": 130, "live": 55, "type": ["Water"]},
    {"id": 100, "name": "Voltorb", "attack": 30, "live": 40, "type": ["Electric"]},
    {"id": 101, "name": "Electrode", "attack": 50, "live": 60, "type": ["Electric"]},
    {"id": 102, "name": "Exeggcute", "attack": 40, "live": 60, "type": ["Grass", "Psychic"]},
    {"id": 103, "name": "Exeggutor", "attack": 95, "live": 95, "type": ["Grass", "Psychic"]},
    {"id": 104, "name": "Cubone", "attack": 50, "live": 50, "type": ["Ground"]},
    {"id": 105, "name": "Marowak", "attack": 80, "live": 60, "type": ["Ground"]},
    {"id": 106, "name": "Hitmonlee", "attack": 120, "live": 50, "type": ["Fighting"]},
    {"id": 107, "name": "Hitmonchan", "attack": 105, "live": 50, "type": ["Fighting"]},
    {"id": 108, "name": "Lickitung", "attack": 55, "live": 90, "type": ["Normal"]},
    {"id": 109, "name": "Koffing", "attack": 65, "live": 40, "type": ["Poison"]},
    {"id": 110, "name": "Weezing", "attack": 90, "live": 65, "type": ["Poison"]},
    {"id": 111, "name": "Rhyhorn", "attack": 85, "live": 80, "type": ["Ground", "Rock"]},
    {"id": 112, "name": "Rhydon", "attack": 130, "live": 105, "type": ["Ground", "Rock"]},
    {"id": 113, "name": "Chansey", "attack": 5, "live": 250, "type": ["Normal"]},
    {"id": 114, "name": "Tangela", "attack": 55, "live": 65, "type": ["Grass"]},
    {"id": 115, "name": "Kangaskhan", "attack": 95, "live": 105, "type": ["Normal"]},
    {"id": 116, "name": "Horsea", "attack": 40, "live": 30, "type": ["Water"]},
    {"id": 117, "name": "Seadra", "attack": 65, "live": 55, "type": ["Water"]},
    {"id": 118, "name": "Goldeen", "attack": 67, "live": 45, "type": ["Water"]},
    {"id": 119, "name": "Seaking", "attack": 92, "live": 80, "type": ["Water"]},
    {"id": 120, "name": "Staryu", "attack": 45, "live": 30, "type": ["Water"]},
    {"id": 121, "name": "Starmie", "attack": 75, "live": 60, "type": ["Water", "Psychic"]},
    {"id": 122, "name": "MrMime", "attack": 45, "live": 40, "type": ["Psychic", "Fairy"]},
    {"id": 123, "name": "Scyther", "attack": 110, "live": 70, "type": ["Bug", "Flying"]},
    {"id": 124, "name": "Jynx", "attack": 50, "live": 65, "type": ["Ice", "Psychic"]},
    {"id": 125, "name": "Electabuzz", "attack": 83, "live": 65, "type": ["Electric"]},
    {"id": 126, "name": "Magmar", "attack": 95, "live": 65, "type": ["Fire"]},
    {"id": 127, "name": "Pinsir", "attack": 125, "live": 65, "type": ["Bug"]},
    {"id": 128, "name": "Tauros", "attack": 100, "live": 75, "type": ["Normal"]},
    {"id": 129, "name": "Magikarp", "attack": 10, "live": 20, "type": ["Water"]},
    {"id": 130, "name": "Gyarados", "attack": 125, "live": 95, "type": ["Water", "Flying"]},
    {"id": 131, "name": "Lapras", "attack": 85, "live": 130, "type": ["Water", "Ice"]},
    {"id": 132, "name": "Ditto", "attack": 48, "live": 48, "type": ["Normal"]},
    {"id": 133, "name": "Eevee", "attack": 55, "live": 55, "type": ["Normal"]},
    {"id": 134, "name": "Vaporeon", "attack": 65, "live": 130, "type": ["Water"]},
    {"id": 135, "name": "Jolteon", "attack": 65, "live": 65, "type": ["Electric"]},
    {"id": 136, "name": "Flareon", "attack": 130, "live": 65, "type": ["Fire"]},
    {"id": 137, "name": "Porygon", "attack": 60, "live": 65, "type": ["Normal"]},
    {"id": 138, "name": "Omanyte", "attack": 40, "live": 35, "type": ["Rock", "Water"]},
    {"id": 139, "name": "Omastar", "attack": 60, "live": 70, "type": ["Rock", "Water"]},
    {"id": 140, "name": "Kabuto", "attack": 80, "live": 30, "type": ["Rock", "Water"]},
    {"id": 141, "name": "Kabutops", "attack": 115, "live": 60, "type": ["Rock", "Water"]},
    {"id": 142, "name": "Aerodactyl", "attack": 105, "live": 80, "type": ["Rock", "Flying"]},
    {"id": 143, "name": "Snorlax", "attack": 110, "live": 160, "type": ["Normal"]},
    {"id": 144, "name": "Articuno", "attack": 85, "live": 90, "type": ["Ice", "Flying"]},
    {"id": 145, "name": "Zapdos", "attack": 90, "live": 90, "type": ["Electric", "Flying"]},
    {"id": 146, "name": "Moltres", "attack": 100, "live": 90, "type": ["Fire", "Flying"]},
    {"id": 147, "name": "Dratini", "attack": 64, "live": 41, "type": ["Dragon"]},
    {"id": 148, "name": "Dragonair", "attack": 84, "live": 61, "type": ["Dragon"]},
    {"id": 149, "name": "Dragonite", "attack": 134, "live": 91, "type": ["Dragon", "Flying"]},
    {"id": 150, "name": "Mewtwo", "attack": 110, "live": 106, "type": ["Psychic"]},
    {"id": 151, "name": "Mew", "attack": 100, "live": 100, "type": ["Psychic"]}
]